# Overview: This workflow has the purpose of running continous integration tests and ensure that the app can be built
# sucessfully

name: Continuous Integration
on: 
  push:
    branches:
      - "**" 
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
      - name: Check version
        run: flutter --version
      - name: Get Packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Compile translation file
        run: flutter gen-l10n
      - name: Run tests
        run: flutter test
